### ISSUE TITLE
feature request: JSON multiline snapshot support

### ISSUE THREAD

**Issue by yannvr** [syrusakbary/snapshottest#100]
Given that most API endpoints return JSON responses. Could we have the snapshot formatted as JSON? Moving away from a single line snapshot would allow to verify line by line responses before adding a new snapshot.  
For instance, a snapshot could look like that:
```
// Snapshot
exports[`returns data for id = 3`] = `
{
  "id": 3,
  "name": "LeBron James",
}
`;
```
instead of
``` 
exports[`returns data for id = 3`] = ` {"id": 3,"name": "LeBron James",}`;
```

**Comment by paulmelnikow** [comment]
I suspect this could be accomplished by transforming the JSON object back to a formatted JSON string before passing it to snapshot, in conjunction with functionality in snapshottest to format multi-line string snapshots as multi-line strings in the generated Python source.

**Comment by medmunds** [comment]
BTW, snapshottest *does* already format multi-line strings as nice, triple-quoted string blocks.

But you might actually be happier snapshotting the parsed JSON. Then your snapshot will be formatted as Python dicts and lists, and you should get really nice diffs:

```python
def test_something(self):
    response = self.client.get("/something")
    self.assertMatchSnapshot(response.json())  # <-- note the `.json()`
```

results in:

```python
# snapshottest: v1 - https://goo.gl/zC4yUc
# ...
snapshots['TestDemo::test_api_me 1'] = {
    'id': 3,
    'name': 'LeBron James'
}

```

Both the Django TestClient and python-requests support `response.json()` to easily grab a response as parsed JSON. I'm guessing many other Python API wrappers have this feature, too.

(Also, @yannvr your code seems to be in JavaScript. I'm guessing you were just making up an example, but wanted to double check you didn't actually mean to request a feature for the Jest package.)

**Comment by yannvr** [comment]
Thanks for your reply gents!
@medmunds, yes code was in JS. That's how I started comparing the merits of snapshots single line vs multi line.
I'm very happy the solutions you're offering. Closing the issue
