### ISSUE TITLE
Feature Request : Skip the fields in API Response for assertmatch

### ISSUE THREAD

**Issue by jayeshguru** [syrusakbary/snapshottest#105]
We have some APIs where the response has queryTime in it and it varies for each api response.
This is avoiding us to use snapshots in our tests as it always fails.
Therefore, I request for a feature which will allow us to bypass some fields in the api response to be snapshot matched.

**Comment by HeyHugo** [comment]
See #102

**Comment by paulmelnikow** [comment]
Let's track this in #21.
