### ISSUE TITLE
Formatters fail on typed enums

### ISSUE THREAD

**Issue by VladV** [syrusakbary/snapshottest#120]
Default formatters produce invalid output when processing typed enum values, e.g. inherited from `enum.IntEnum` or `(str, enum.Enum)`.

Example:
```
from enum import Enum
from collections import defaultdict
from snapshottest.formatter import Formatter

class N(str, Enum):
  A = 'a'

f = Formatter(defaultdict(set))
print(f.format(N.A, ''))
```

This produces `<N.A: 'a'>`, which results in a syntax error when printed into a snapshot file.

Suggested fix: modify `TypeFormatter.can_format` so that it skips enums, and they are processed by GenericFormatter.

**Comment by paulmelnikow** [comment]
Related to #127. Would welcome a PR to fix this!
