### ISSUE TITLE
Require Python 3

### ISSUE THREAD

**Issue by paulmelnikow** [syrusakbary/snapshottest#124]
Since Python 2 has been deprecated, I suggest we drop support for it the next major release. Many libraries, including developer tools, have done so… pip, pytest, etc.

IMO it is not worth spending the limited volunteer development efforts we have to keep this working on an obsolete platform.

**Comment by mvbrn** [comment]
That's a good idea! 
Especially those lines on the beginning of each snapshot are annoying:
```
# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals
```
