### ISSUE TITLE
Django test database not flushed and/or transaction not rolled back unless specifying django.test.TestCase mixin

### ISSUE THREAD

**Issue by mcabrams** [syrusakbary/snapshottest#139]
I'm seeing issues of data either not being flushed after each snapshottest.TestCase unless I specifically include a mixin for django.test.TestCase.  I think the issue appears when a snapshot fails (data persists into next test case).

Here's the code I originally had:

```python
from django.test import TestCase
from snapshottest import TestCase as SnapshotTestCase

class FooTestCase(SnapshotTestCase):
    def test_foo(self):
        # Create some instances of models in the database
        # Have some assertions that fail

class BarTestCase(SnapshotTestCase):
    def test_bar(self):
        # Filter for instances created in `test_foo` and 
        # you will find them (or they just may break your test here)
```

Changing to this eliminated the issue for me:

```python
from django.test import TestCase
from snapshottest import TestCase as SnapshotTestCase

class FooTestCase(TestCase, SnapshotTestCase):
    def test_foo(self):
        # Create some instances of models in the database
        # Have some assertions that fail

class BarTestCase(TestCase, SnapshotTestCase):
    def test_bar(self):
        # Filter for instances created in `test_foo` and you won't find them
```

Seeing from #1 and looking at the source, `TestCase` is clearly inherited from, so that should not be the issue.  I'm assuming there is some logic in test cleanup that has been overriden?  I'm not sure.

**Comment by paulmelnikow** [comment]
Hi! Which release of snapshottest are you using? Could you check if this is reproducible in both 0.5.1 and 0.6.0?

**Comment by mcabrams** [comment]
I was on 0.6.0 - checked 0.5.1 and I have the same issue

**Comment by medmunds** [comment]
You're using the *non-Django* version of snapshottest's TestCase, which doesn't include Django's code to reset the DB between tests. (The naming is super confusing here. But Django kind of started it.)

The fix should be:

```python
# Change
from snapshottest import TestCase as SnapshotTestCase
# To:
from snapshottest.django import TestCase as SnapshotTestCase
```

Your mixin approach does exactly the same thing as [snapshottest.django.TestCase](https://github.com/syrusakbary/snapshottest/blob/0.6.0/snapshottest/django.py#L56).

**Comment by mcabrams** [comment]
Thanks very much @medmunds, sorry I missed that!  Closing this issue.
