### ISSUE TITLE
Named snapshots

### ISSUE THREAD

**Issue by tricoder42** [syrusakbary/snapshottest#17]
Hey, great project, thanks a lot!

What's your opinion on named snapshots? Right now the name is auto-generated from the name of method where it's called and number of occurrence. It would help me to check snapshots manually if I could set the name, something like:

```py
def test_serializers(snapshot):
    snapshot.assert_match(serializer(Project.objects.all()), 'projects')
    snapshot.assert_match(serializer(Role.objects.all()), 'roles')
```

... and the snapshots would be named `test_serializers projects`, `test_serializers roles` and so on.

What do you think?

**Comment by syrusakbary** [comment]
I think that's a great idea!
In can work like:

```
def test_serializers(snapshot):
    snapshot.assert_match(serializer(Project.objects.all())) # -> Default one, using the counter
    snapshot.assert_match(serializer(Role.objects.all()), 'roles') # -> Using the provided index name
```

If you wanna create a PR I will happily merge it :)

**Comment by tricoder42** [comment]
PR ready, docs updated! Review welcome 👍  Cheers 🎉
