### ISSUE TITLE
Please accept new maintainers

### ISSUE THREAD

**Issue by intgr** [syrusakbary/snapshottest#174]
Hi! It's clear that this project is suffering from lack of maintenance lately.

The most pressing issue is Python 3.12 support (#166, #168, #173). Python 3.12 was released now over 7 months ago. Last "alpha" 1.0.0a0 release of snapshottest was 3.5 years ago.

While initially in 2023 October, #168 was reviewed and even ostensibly approved, since then here has been complete silence from anyone with apparent authority in this project, despite multiple pings in various locations.

@syrusakbary @davidshepherd7 @paulmelnikow Please confirm if you would like to figure out a way to find additional maintainers to this project. Alternatively, if you don't wish undertake that responsibility (perhaps understandable in the wake of XZ drama), please clearly declare this project unmaintained and dead.

**Comment by ayys** [comment]
@intgr thanks for bringing this up. I have been talking to syrus, and he has given me push access to the repository. Since I am using snapshottest extensively on a daily basis I hope to be able to put some energy back into the project and remove some of the stagnation.

As a start, I have merged PR #168.

**Comment by ayys** [comment]
@bassco already done https://pypi.org/project/snapshottest/1.0.0a1/
I think I did it right around when you asked!

**Comment by ayys** [comment]
Lets use this thread as the place to let me know of any PRs anyone thinks should be prioritized, and I will work on that.

**Comment by ayys** [comment]
Closing this thread for now since I am maintaining this repo.
