### ISSUE TITLE
Custom Names?

### ISSUE THREAD

**Issue by KaySackey** [syrusakbary/snapshottest#22]
In the documentation it claims you can set a custom name ,e.g.

>  Set custom snapshot name: `gpg_response`

However the actual code doesn't support that. Was this supposed to be implemented?

**Comment by huntie** [comment]
It has been implemented in #18, however no release of this project has been made since then :|

**Comment by ygormutti** [comment]
Right now you can use this feature by referencing the commit hash in your `requirements.txt` or `Pipfile`.

Another issue that could be closed just by publishing a new version to PyPI. cc @yourbuddyconner @syrusakbary
