### ISSUE TITLE
Sort order of OrderedDicts when snapshotting ?

### ISSUE THREAD

**Issue by peritus** [syrusakbary/snapshottest#3]
Hey,

just found your package, I'm super happy with jest snapshots and want to write tests for troposphere cloud formation templates (https://github.com/cloudtools/troposphere). They are large JSON templates and troposphere returns them as an ordinary dict.

So, OrderedDict to the rescue:

```
import json
from collections import OrderedDict

from mycompany.troposphere import cftemplate


class SortedDict(OrderedDict):
    def __init__(self, **kwargs):
        super(SortedDict, self).__init__()

        for key, value in sorted(kwargs.items()):
            if isinstance(value, dict):
                self[key] = SortedDict(**value)
            else:
                self[key] = value


def test_cftemplate(snapshot):
    snapshot.assert_match(
        SortedDict(**(
          json.loads(
              cftemplate.to_json(),
              object_pairs_hook=OrderedDict)
          )
        )
    )
```

(combining http://stackoverflow.com/a/31483810 here with http://stackoverflow.com/a/6921760 )

-----

But I guess that is all I can do as a test author, because the snapshot is serialized as an ordinary dict like this:

```

from snapshottest import Snapshot


snapshots = Snapshot()

snapshots['test_cftemplate 1'] = {
    'Conditions': {

```

and then also read as an ordinary dict when importing (and then the order is undefined again).

-----

Hence my question:

How do I make both the snapshot and the received value be a `SortedDict` before comparing ?

**Comment by peritus** [comment]
It seems to work for _comparison_ but once there is a difference, the diff is way off.

**Comment by jmsegrev** [comment]
I'm also having this issue, @peritus have you come up with any solution?.

**Comment by peritus** [comment]
@jmsegrev I just don't use the fancy pytest diff (little sad about that) and use it only to detect that there is *a* difference. Once there is one, I update the snapshot and look at the output of "git diff".

**Comment by jsep** [comment]
@jmsegrev @peritus Please test my PR (#4), this issue should be solved.

@peritus I'm using your code to sort the dicts.

Thanks
