### ISSUE TITLE
When can we expect release 0.5.1

### ISSUE THREAD

**Issue by eldos-dl** [syrusakbary/snapshottest#37]
Any plans on publishing latest changes to pip?
Any plans on setting up CD with Travis to pip?

**Comment by matangover** [comment]
@syrusakbary could I help with this? What's blocking?

**Comment by ljades** [comment]
I would also like to know about this. My application requires using custom snapshot names and the latest pip release doesn't have this functionality.

**Comment by adokania** [comment]
@matangover @syrusakbary could we get a release of the latest changes?

**Comment by matangover** [comment]
@adokania I'm not the package maintainer, I don't have the PyPI  credentials.
Feel free to install from GitHub:
```sh
pip install https://github.com/syrusakbary/snapshottest/archive/master.tar.gz
```

**Comment by ljades** [comment]
@matangover Despite no pip releases, is there a possibility for a release to be tagged just on GitHub? My project is uneasy about pip installing directly from master, since it's a dependency that goes in a requirements file for a virtual environment.

**Comment by matangover** [comment]
I don't have commit rights to this repo. You can install from a specific commit SHA instead of directly from master:
```
pip install https://github.com/syrusakbary/snapshottest/archive/0b4656a156b22221674dd4c1233c849bb03e28f3.tar.gz
```

**Comment by ygormutti** [comment]
@eldos-dl anytime soon! The author gave commit rights to a new maintainer (see #81).

I think setting up CD is a great idea.

@syrusakbary can you please encrypt the PyPI password using `travis` CLI and publish it? Reference: https://docs.travis-ci.com/user/deployment/pypi/

**Comment by yourbuddyconner** [comment]
Continuous Releases is one feature I want to implement right away, see issue here: https://github.com/yourbuddyconner/pysnap/issues/4

Once I get Push access to PyPi I can set it up.

**Comment by yourbuddyconner** [comment]
See #84 for the discussion on access to PyPi, and #85 for the discussion on Continuous Release. Closing.
