### ISSUE TITLE
Snapshot does not record / test correctly

### ISSUE THREAD

**Issue by maxim-lian** [syrusakbary/snapshottest#40]
After running with `--snapshot-update`, the library states it passes. 

But then running again without, it raises an error.

Is it to do with there being newlines? This is the start of the output
```
E         - Snapshot
E         + Received
E
E         - ''''\'{"date":946857600000,"returns":0.0343696959}
E         ?    --
E         + ''''{"date":946857600000,"returns":0.0343696959}
E         - '\'{"date":946944000000,"returns":0.0343696959}
E         ? --
E         + '{"date":946944000000,"returns":0.0343696959}
E         - '\'{"date":947030400000,"returns":0.0343696959}
E         ? --
E         + '{"date":947030400000,"returns":0.0343696959}
E         - '\'{"date":947116800000,"returns":0.0343696959}
E         ? --
E         + '{"date":947116800000,"returns":0.0343696959}
E         - '\'{"date":947203200000,"returns":0.0343696959}
```

or related to https://github.com/syrusakbary/snapshottest/pull/39 ?

**Comment by medmunds** [comment]
@maxim-lian can you post the generated snap_ file? (And are you on Python 2?) This looks similar to #44.

**Comment by maxim-lian** [comment]
That looks very similar, I'll close this

This was a few weeks ago, so I moved off snapshottest, to regtest. But I look forward to checking back soon, thanks for all your work on the project
