### ISSUE TITLE
OrderedDict snapshots match different OrderedDict

### ISSUE THREAD

**Issue by medmunds** [syrusakbary/snapshottest#48]
A snapshot of an OrderedDict loses its ordering, which makes it match any other dicts with the same items in a different order:

```python
from collections import OrderedDict

def test_ordered_dict(snapshot):
    # create a snapshot named 'ordered_dict'
    expect = OrderedDict([('one', 1), ('two', 2), ('three', 3)])
    snapshot.assert_match(expect, name='ordered_dict')

    # test that named snapshot against the same items in a different order
    # (this simulates a later run where the actual result has changed)
    wrong = OrderedDict([('three', 3), ('two', 2), ('one', 1)])
    snapshot.assert_match(wrong, name='ordered_dict')  # should fail, but doesn't!

    assert expect == wrong  # will fail (correctly), and pytest will produce a diff
```

The problem is that snapshottest casts all dict subclasses to SortedDicts, in both assert_match (via PrettyDiff) and when writing the snapshot file (via Formatter). That loses OrderedDict's ordering.

I'm not really sure how best to fix this...

* Special-casing OrderedDict would solve *this* issue, but other dict subclasses probably have related problems. (E.g., CaseInsensitiveDict is common for code dealing with HTTP headers. The current assert_match would force those case-*sensitive*, causing false failures. And so on... there are a lot of clever dict subclasses out there.)

* Removing PrettyDiff's cast to SortedDict would partly solve the problem, but lead to less-useful diffs for ordinary dicts. (Which is why SortedDict was added in the first place.)

* Maybe PrettyDiff should delay all casting and prettification until get_diff time, so that PrettyDiff.\_\_eq\_\_ always compares the original objects? And Formatter.format_dict should just write the object's \_\_repr\_\_?

* Maybe assert_match shouldn't use PrettyDiff for dicts? The standard equal assertions in both [pytest](https://docs.pytest.org/en/latest/assert.html#making-use-of-context-sensitive-comparisons) and [unittest](https://docs.python.org/3/library/unittest.html#type-specific-methods) already try to provide helpful dict diffs. (So PrettyDiff is actually kind of undermining their built-in failure reporting. Maybe there should be an option to just skip PrettyDiff altogether?)

**Comment by paulmelnikow** [comment]
Hi, thanks for the report. We're using fastdiff now. Does this problem still exist in latest master?

**Comment by medmunds** [comment]
Let's add a test to find out… (PR follows)

**Comment by paulmelnikow** [comment]
Thank you! 🙌
