### ISSUE TITLE
Is this project not maintained?

### ISSUE THREAD

**Issue by NateScarlet** [syrusakbary/snapshottest#64]
Since latest release already been 4 mounth old

**Comment by batmantis** [comment]
Not sure.  I have a small PR that has been pending for >1 month.

**Comment by clintonb** [comment]
@syrusakbary ???

**Comment by grechut** [comment]
@syrusakbary Please release a fresh version if possible ;)

**Comment by ygormutti** [comment]
Please, see #81. cc @yourbuddyconner

**Comment by yourbuddyconner** [comment]
I will be prioritizing checking in on the current issues and Open PRs this week. Hopefully I'll be able to cut a release this weekend!
