### ISSUE TITLE
SortedDict accepts only string dict keys

### ISSUE THREAD

**Issue by behnam** [syrusakbary/snapshottest#65]
Turns out `SortedDict`, and therefore most of snapshottest API, accepts only string dict keys.

This means it's not possible to take snapshot of dict values that have other values as key, like Enum members.

Repro:
```python
import enum
import collections
import snapshottest

class Fruit(enum.Enum):
    APPLE = 1
    ORANGE = 2


test_value = {
    Fruit.APPLE: 100,
    Fruit.ORANGE: 400,
}

# This works fine...
collections.OrderedDict(**test_value)

# But this throws:
# ```
# TypeError: __init__() keywords must be strings
# ```
snapshottest.sorted_dict.SortedDict(**test_value)
```

Play: https://repl.it/repls/TiredQuerulousTrapezoids

**Comment by RazerM** [comment]
It's also a problem when a dict has `'self'` as a key.
