### ISSUE TITLE
option to disable/bypass PrettyDiff'ing

### ISSUE THREAD

**Issue by hangtwenty** [syrusakbary/snapshottest#75]
in pdb I just want the objects sometimes. would be good to have a CLI flag for this. happy to submit a PR if it would be considered

**Comment by hangtwenty** [comment]
update, not only good for pdb, I'd also just like to have a different approach to diffing overall. When you are definitely always using pytest (we are), you can choose to just-use-regular-asserts, and pytest's diffing kicks in. Plus I want to write a hook to compare dataframes differently, such as with [the `datacompy` library](https://capitalone.github.io/datacompy/pandas_usage.html).

I have a workaround for now of intercepting the `snapshot` instance and monkeypatching it by binding `MethodType` to replace its methods. Have to do this because there are not currently hooks.

Would you be open to a PR adding ability to subclass snapshottest, and pick which subclass to use as a global config setting or fixture hook?

**Comment by ygormutti** [comment]
PrettyDiff usage was dropped in #54, now it uses regular asserts and if you want to use PrettyDiff you need to explicitly wrap the object inside it, like `PrettyDiff(obj, snapshot)`. cc @yourbuddyconner

**Comment by yourbuddyconner** [comment]
Closing as Fixed, please open another issue if this is still bothering you @hangtwenty

**Comment by ygormutti** [comment]
@hangtwenty, almost forgot: now we have a way to customize the way snapshottest saves snapshots. :) For an example, file snapshots (also added in #54) was implemented using this new hook. Please, check: https://github.com/syrusakbary/snapshottest/blob/master/snapshottest/file.py

A PR improving documentation on this feature would be welcome.
