### ISSUE TITLE
Does not install on Alpine - no `wesmer` available

### ISSUE THREAD

**Issue by aviv-ebates** [syrusakbary/snapshottest#88]
Latest version refuses to install on Linux Alpine:

```
$ docker run  -ti --rm python:3.7-alpine sh -c 'pip install -U pip; pip install fastdiff'
Requirement already up-to-date: pip in /usr/local/lib/python3.7/site-packages (19.1.1)
Collecting fastdiff
  Downloading https://files.pythonhosted.org/packages/11/6e/a2bceac267de3deeca904959b966533479cf0ea1031714b09d1af278bfeb/fastdiff-0.1.4-py2.py3-none-any.whl
Collecting wasmer; python_version >= "3.5" and platform_machine == "x86_64" and sys_platform == "linux" (from fastdiff)
  ERROR: Could not find a version that satisfies the requirement wasmer; python_version >= "3.5" and platform_machine == "x86_64" and sys_platform == "linux" (from fastdiff) (from versions: none)
ERROR: No matching distribution found for wasmer; python_version >= "3.5" and platform_machine == "x86_64" and sys_platform == "linux" (from fastdiff)
```

Does install properly on other distros (Ubuntu, `slim`, etc).

Fastdiff requires wesmer, which isn't available for Alpine, so the whole setup fails.

There might be a variant of `extras` to allow explicitly not-install `wesmer`.

**Comment by aviv-ebates** [comment]
Alpine is using `musl libc` where almost everybody else is using `glibc`, so native code needs to be compiled differently.
It's also possible to try to convince `wesmer` to release a `musl` version, or a source release, and then this might work.

**Comment by chadmckenna** [comment]
I'm running into the same issue with Alpine. Weirdly, the `python:3.4-alpine` image seems to work fine.  It looks like it has something to do with the `setup.py` file for `fastdiff` (https://github.com/syrusakbary/fastdiff/blob/master/python/setup.py#L16). It looks like `fastdiff` has a fallback option, but its only for 3.4 and before.

**Comment by chadmckenna** [comment]
@aviv-ebates I rolled my version of snapshottest back to be exactly`0.5.0` for now to get it to build, it looks like the `wasmer` dependency was added for the `0.5.1` version.

**Comment by syrusakbary** [comment]
We will resolve this soon. Thanks for the ping!

**Comment by syrusakbary** [comment]
This now should be solved. Can someone confirm?

**Comment by aviv-ebates** [comment]
Looks good to me:
```
$ docker run  -ti --rm python:3.7-alpine sh -c 'pip install -U pip; pip install snapshottest'
   ...
   ...
   ...
Installing collected packages: six, termcolor, wasmer, fastdiff, snapshottest
Successfully installed fastdiff-0.2.0 six-1.12.0 snapshottest-0.5.1 termcolor-1.1.0 wasmer-0.3.0
```

And running all my tests now works (and passes) on Alpine.

Thanks!

**Comment by syrusakbary** [comment]
Awesome. Closing issue

**Comment by chadmckenna** [comment]
Can confirm, fixes my issues as well, thanks @syrusakbary!
