### ISSUE TITLE
Conflicts with black

### ISSUE THREAD

**Issue by paulmelnikow** [syrusakbary/snapshottest#89]
Hi! Thanks for this useful tool!

When I save out new snapshots, they aren't in the format recognized by Black, which involves running the formatter a second time. This is a little fiddly, and I don't really care about having the format just so, so I would prefer to automatically ignore these files.

Some possible solutions:

1. Add
    ```py
    # fmt: off
    ```
    to the block at the top of the snapshot file. I've tested this, it works, and it's easy.
2. Let people decide whether they want this header. I'd turn it on by default – since it's a good default – and let people turn it off if they _really_ want their files formatted by Black.
3. If Black is available, before writing the file, attempt to run the output through Black. Let users disable this behavior in config. I like this option best because it's a very nice developer experience (even though it would be a little inconvenient for my use case, which sadly is a lib that has Python 2 deps, so I can't run tests and Black in the same env).
4. Try to modify the output to cohere to Black's demands. I expect this is impractical.

With some guidance about which way to go, I'd be happy to contribute this.

**Comment by ygormutti** [comment]
You can configure Black to ignore snapshots by using the `--exclude` option: 
```
black . --exclude '.*/snapshots/.*
```
I'd rather keep snapshottest ignorant about Black (because a lot of projects use other formatters, like autopep8, yapf, etc), and instead document how to ignore snapshots in formatters. All mentioned formatters have an exclude option.

**Comment by paulmelnikow** [comment]
That's a possibility, and what I'm doing now, though I'm not convinced it's the best way to handle this.

I've already had two sets of PRs where this churned. One of the developers on my team must have edited the snapshot in his editor. Probably this is because the snapshot is testing something that takes a while to run, so computing the values affected by his changes and pasting them in was faster than running the entire thing.

Black unfortunately (unless I missed it) does not have a way to exclude a path via configuration, only the command line. That means that autoformat on save has no way of knowing the file should be excluded.

I guess my other alternative at this point is to reformat after writing new snapshots. That's not a great plan though I'd prefer that to these churning diffs.

Alternatively Black could add a config option for the excludes.

**Comment by paulmelnikow** [comment]
Update: It looks like black does have a config option for the excludes, though it sometimes seems to be ignored.

This has caused several conflicts in the project I'm working on so I've given up on solving it for now. I've configured black to require the file to be formatted instead. This adds a second step when updating snapshots, but it at least makes review consistently easier.

**Comment by ygormutti** [comment]
This usually helps with me when I open a snapshot and accidentaly format it (I'm a compulsive formatter, lol). It seems this could help us both: https://github.com/psf/black#pyprojecttoml

**Comment by paulmelnikow** [comment]
> This usually helps with me when I open a snapshot and accidentaly format it (I'm a compulsive formatter, lol). It seems [this configuration option](https://github.com/psf/black#pyprojecttoml) could help us both if our text editors respect it. Haven't tested it though. Is this the "config option" you mentioned?

Yes. That option works when I run black from the command line on an entire folder, though not when it's run by the editor on a single file. I'm not sure if the problem is that if the config file isn't being read, or if the config file is in conflict with the command line args and the command line takes precedence.

**Comment by martijnthe** [comment]
How about adding a formatter hook to snapshottest and let people choose whatever formatter they like?

**Comment by skovhus** [comment]
Ideally, auto-generated files shouldn't be formatted, so adding a `# fmt: off` line seems like a very simple solution to this problem compared to adding a formatting hook. 

@syrusakbary would you accept a PR adding a `# fmt: off` line?

**Comment by wowkin2** [comment]
I would rather make these auto-generated files configurable so they would match code conventions in my project, so they would not need to be formatted :slightly_smiling_face: 
Thinking that PR https://github.com/syrusakbary/snapshottest/pull/149 from @kam193 should work and not break anything in existing functionality for others who just exclude snapshots.
