### ISSUE TITLE
Proposed fork / extras_require

### ISSUE THREAD

**Issue by dfee** [syrusakbary/snapshottest#9]
Tonight, when upgrading, I noticed my virtualenv had been muddied by the addition(s) from a django requirement. I don't use django, and I don't think this library requires django (except for the django specific code in [`django.py`](https://github.com/syrusakbary/snapshottest/blob/master/snapshottest/django.py)).

Can we move this code to either /ext/django and use setup.py's `extras_require={'django': [django]}` so this library can have a broader audience than those intererested in django development?

**Comment by syrusakbary** [comment]
I removed the django dependency in this commit: https://github.com/syrusakbary/snapshottest/commit/37eb0d2f17545cd1f216a9d1d0db6869f374e6a0

The recently uploaded version 0.5.0 should have the django-dependency issue fixed :)

**Comment by dfee** [comment]
Awesome. Thanks @syrusakbary
