### ISSUE TITLE
Changelog update / commit tagging

### ISSUE THREAD

**Issue by bluefish6** [syrusakbary/snapshottest#91]
Hi, a lot has changed between 0.5 and 0.5.1 (released to pypi), but the changelog is not updated yet. Could you please update the changelog?

It would be also nice to tag specific commits with versions released to pypi, so it would be easy to compare "current" with "old" version even without a changelog.

**Comment by paulmelnikow** [comment]
Hi, thanks for this request. I totally agree. Would anyone who is following this repo be up for tracking down the commits for 0.5 and 0.5.1 and letting me know what they are? Then I could push the tags. Then the next step is to write the changelog. Would be great if someone could take that on as well!

**Comment by paulmelnikow** [comment]
I've tagged 0.5.0 and 0.5.1. If anyone would like to write the changelog for 0.5.1 I'd welcome it!

https://github.com/syrusakbary/snapshottest/compare/0.5.0...0.5.1
